### ISSUE TITLE
Disable login and directly get to home page

### ISSUE THREAD

**Issue by mehdi-aouadi** [chatelao/php-addressbook#10]
Hello,

Is there a way to disable login and directly get to addressbook or set a default readonly mode connection ?

Regards.

**Comment by k1rb** [comment]
I haven't looked at the configs too closely but I'd also like to know this.

Thanks guys!

**Comment by chatelao** [comment]
You can whitelist IPs
I think you should be able to make readonly public

**Comment by k1rb** [comment]
@chatelao
My bad. Right after you said this I checked the manual and found that this is even documented. I have it working now. I appreciate your time.

**Comment by chatelao** [comment]
That's no problem at all thank you very much.

bfrd <notifications@github.com> schrieb am So., 19. Nov. 2017, 20:21:
